api:
  deploymentName: "api-deployment"
  label: "api"
  replicas: "2"
  image:
    registry: "ahp1609"
    repository: "api"
    tag: "v1"
  port: "5005"
  serviceName: "api-service"
  ingressName: "api-ingress"
  ingressclassName: "nginx"
  path: "/api/"

ui:
  deploymentName: "ui-deployment"
  label: "ui"
  replicas: "2"
  image:
    registry: "ahp1609"
    repository: "ui"
    tag: "latest"
  port: "3000"
  service: "ui-service"
  ingress: "rech-ingress"
  ingressclassName: "nginx"
  path: "/"

